language: java
install: true
script:
  - mvn install
  - mvn package

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://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@github.com/Kamool/AplsoftRed-report-system --tags

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 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
  file:
    - "Reporter_repo-1.0-SNAPSHOT-shaded"
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/