language: java
install: true
script:
  - mvn install
  - mvn package

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: "Reporter_repo-1.0-SNAPSHOT-shaded.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true